// flow-typed signature: 7489f6fb58e520b468194547ad0d13dd
// flow-typed version: <<STUB>>/react-ui-tree_v3.1.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-ui-tree'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-ui-tree' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-ui-tree/dist/node' {
  declare module.exports: any;
}

declare module 'react-ui-tree/dist/react-ui-tree' {
  declare module.exports: any;
}

declare module 'react-ui-tree/dist/tree' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-ui-tree/dist/node.js' {
  declare module.exports: $Exports<'react-ui-tree/dist/node'>;
}
declare module 'react-ui-tree/dist/react-ui-tree.js' {
  declare module.exports: $Exports<'react-ui-tree/dist/react-ui-tree'>;
}
declare module 'react-ui-tree/dist/tree.js' {
  declare module.exports: $Exports<'react-ui-tree/dist/tree'>;
}
declare module 'react-ui-tree/index' {
  declare module.exports: $Exports<'react-ui-tree'>;
}
declare module 'react-ui-tree/index.js' {
  declare module.exports: $Exports<'react-ui-tree'>;
}
